script: rake test
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - jruby-head
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: jruby-head
    - rvm: rbx-19mode
    - rvm: ruby-head
